
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-apps-commonpool-net-v1-commonpoolinstallation
  failurePolicy: Fail
  name: mcommonpoolinstallation.kb.io
  rules:
  - apiGroups:
    - apps.commonpool.net
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - commonpoolinstallations

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-apps-commonpool-net-v1-commonpoolinstallation
  failurePolicy: Fail
  name: vcommonpoolinstallation.kb.io
  rules:
  - apiGroups:
    - apps.commonpool.net
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - commonpoolinstallations
