apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: commonpool@protonmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: commonpool-cert-prod
    solvers:
    - selector:
        dnsZones:
          - "commonpool.net"
          - "*.commonpool.net"
      dns01:
        route53:
          region: us-east-1
          hostedZoneID: Z099637722IJL00LBV98X