# permissions for end users to edit commonpoolinstallations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: commonpoolinstallation-editor-role
rules:
- apiGroups:
  - apps.commonpool.net
  resources:
  - commonpoolinstallations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.commonpool.net
  resources:
  - commonpoolinstallations/status
  verbs:
  - get
