# permissions for end users to view commonpoolinstallations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: commonpoolinstallation-viewer-role
rules:
- apiGroups:
  - apps.commonpool.net
  resources:
  - commonpoolinstallations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.commonpool.net
  resources:
  - commonpoolinstallations/status
  verbs:
  - get
